### ISSUE TITLE
[TO-DO] 20240628

### ISSUE THREAD

**Issue by kyj4528** [Do-10-to-10/Study#6]
노력한 흔적 남기기!

**Comment by kyj4528** [comment]
✅ java 알고리즘 3문제
✅ spring 개념 공부
✅ 자소서 한 문항 작성
✅ 내일배움카드 신청

**Comment by hyoom** [comment]
✅ 코테(파이썬) 1문제
❎ 스프링 MVC 1편 - 백엔드 웹 개발 핵심 기술 섹션 1
✅ java 강의 섹션 2까지
✅ 노트북 포맷 환경 설정
